- name: Configuring the Frontend
  hosts: frontend
  become: yes

  tasks:
  - name: Change hostname to frontend
    hostname:
      name: frontend.trivikram.online

  - name: Disable current module
    dnf:
      name: nginx
      state: removed

  - name: Enable nginx 1.24 version
    command: dnf module enable nginx:1.24 -y

  - name: Install nginx
    package:
      name: nginx
      state: present
  
  - name: Delete the Entire html directory
    file:
      path: /usr/share/nginx/html/
      state: absent

  - name: Delete frontend.zip in tmp directory
    file:
      path: /tmp/frontend.zip
      state: absent

  - name: Create the HTML directory
    file: 
      path: /usr/share/nginx/html/
      state: directory

  - name: Download frontend code file
    get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip 
      dest: /tmp/frontend.zip
  
  - name: Unzip the .zip file
    unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html/
      remote_src: yes

  - name: Delete the default nginx conf file
    file:
      path: /etc/nginx/nginx.conf
      state: absent

  - name: copy the nginx conf file
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf

  - name: Start and Enable nginx
    service:
      name: nginx
      state: restarted
      enabled: yes