- name: Configuring Redis Server
  hosts: redis
  become: yes
  tasks:
  - name: Change hostname
    hostname:
      name: redis.trivikram.online

  - name: Disabling default redis 6
    dnf:
      name: redis
      state: removed
  
  - name: enable redis 7
    command: dnf module enable redis:7 -y
    tags:
      redis

  - name: Installing Redis 
    package:
      name: redis
      state: present

  - name: Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/redis/redis.conf
    replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: Update protected-mode from yes to no in /etc/redis/redis.conf
    lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: 'protected-mode no'


  - name: Start & Enable Redis Service
    service:
      name: redis
      state: started
      enabled: yes
