- name: Configuring catalogue service setup
  hosts: catalogue
  become: yes
  tasks:
  - name: Change hostname
    hostname:
      name: catalogue.trivikram.online

  - name: Disable current module
    dnf:
      name: nodejs
      state: removed
  
  - name: enable nodejs 20
    command: dnf module enable nodejs:20 -y
  
  - name: Install NodeJS
    package:
      name: nodejs
      state: present

  - name: Add application User - system
    user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: roboshop system user
    tags:
      - catalogue
    
  - name: Remove directory if it exists 
    file:
      path: /app
      state: absent

  - name: delete .zip file in /app directory if it exists
    file:
      name: /tmp/catalogue-v3.zip
      state: absent

  - name : Create directory /app
    file:
      name: /app
      state: directory
  
  - name:
    get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/
    
  - name: unzip catalogue.zip file
    unarchive:
      src: /tmp/catalogue-v3.zip
      dest: /app
      remote_src: yes
  
  - name: Download the dependencies
    community.general.npm:
      path: /app
  - name:
    template:
      src: catalogue.service.j2
      dest: /etc/systemd/system/catalogue.service

  - name: copy mongo.repo
    copy: 
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install mongodb-client
    package:
      name: mongodb-mongosh
      state: present

  - name: Check schema exists or not in mongodb
    shell: mongosh --host "{{ MONGODB_HOST }}" --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output
    tags:
      -mongodb
  
  - name: print catalogue_output
    debug: 
      msg: "{{ catalogue_output }}"
    tags:
      -mongodb
  
  - name: Load the data / products
    shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
    when: catalogue_output.stdout | int < 0
    tags:
      - mongodb

  - name: systemd reload
    systemd_service:
      name: catalogue
      daemon_reload: true
    when: catalogue.service.changed
    tags:
      - system-reload

  - name: Start and Enable the service
    service:
      name: catalogue
      state: restarted # stop and starts the service no matter what

