[local]
localhost

[mongodb]
mongodb.trivikram.online

[redis]
redis.trivikram.online

[mysql]
mysql.trivikram.online

[rabbitmq]
rabbitmq.trivikram.online

[catalogue]
catalogue.trivikram.online

[user]
user.trivikram.online

[cart]
cart.trivikram.online

[shipping]
shipping.trivikram.online

[payment]
payment.trivikram.online

[frontend]
frontend.trivikram.online